GET http://127.0.0.1:5000/directors/
###
GET http://127.0.0.1:5000/directors/1
###
POST http://127.0.0.1:5000/directors/
Content-Type: application/json

    {
        "fullName" : "Michael Bay",
        "birthYear": 1965,
        "nationality": "USA"
    }
###
PUT http://127.0.0.1:5000/directors/2
Content-Type: application/json

    {
        "id": 2,
        "fullName": "Christopher Nolan",
        "birthYear": 1970,
        "nationality": "United Kingdoms"
    }
###
DELETE http://127.0.0.1:5000/directors/2
###
# Studio requests
###
GET http://127.0.0.1:5000/studios/
###
GET http://127.0.0.1:5000/studios/1
###
POST http://127.0.0.1:5000/studios/
Content-Type: application/json

    {
        "title" : "Disney",
        "location": "Washington"
    }
###
PUT http://127.0.0.1:5000/studios/2
Content-Type: application/json

    {
        "id": 2,
        "title": "Pinewood Studios",
        "location": "London"
    }
###
DELETE http://127.0.0.1:5000/studios/2
###
###
# Movie requests
###
GET http://127.0.0.1:5000/movies/
###
GET http://127.0.0.1:5000/movies/1
###
POST http://127.0.0.1:5000/movies/
Content-Type: application/json

    {
        "title" : "Blade Runner",
        "directorId": 0,
        "studioId": 0
    }
###
PUT http://127.0.0.1:5000/movies/1
Content-Type: application/json

    {
        "id": 1,
        "title": "Star Wars: The Rogue One",
        "directorId": 1,
        "studioId": 1
    }
###
DELETE http://127.0.0.1:5000/movies/1
###